#ifndef INGAME_EVENT_EV_LOAD_H
#define INGAME_EVENT_EV_LOAD_H

#include "typedefs.h"

typedef struct {
	u_short file_no;
	u_char file_type;
	u_char tmp_no;
	u_int addr;
} MSN_LOAD_DAT;

typedef struct {
	u_char scn_no;
	MSN_LOAD_DAT *load_dat;
	u_short *del_dat;
} SCN_LOAD_DAT;

typedef struct {
	u_char mode;
	u_char count;
	int load_id;
} EVENT_LOAD_WRK;

typedef struct {
	u_char mode;
	u_char load_mode;
	u_char load_count;
	u_char time;
	int load_id;
} MSN_TITLE_WRK;

// extern MSN_LOAD_DAT msn0_title_load_dat[0];
// extern MSN_LOAD_DAT scn0022_load[0];
// extern u_short scn0022_del_dat[0];
// extern SCN_LOAD_DAT scn_load0[0];
// extern MSN_LOAD_DAT msn1_title_load_dat[0];
// extern MSN_LOAD_DAT scn1010_load[0];
// extern u_short scn1010_del_dat[0];
// extern MSN_LOAD_DAT scn1030_load[0];
// extern u_short scn1030_del_dat[0];
// extern MSN_LOAD_DAT scn1034_load[0];
// extern u_short scn1034_del_dat[0];
// extern MSN_LOAD_DAT scn1160_load[0];
// extern u_short scn1160_del_dat[0];
// extern MSN_LOAD_DAT scn1070_load[0];
// extern u_short scn1070_del_dat[0];
// extern MSN_LOAD_DAT scn1090_load[0];
// extern u_short scn1090_del_dat[0];
// extern MSN_LOAD_DAT scn1100_load[0];
// extern u_short scn1100_del_dat[0];
// extern MSN_LOAD_DAT scn1102_load[0];
// extern u_short scn1102_del_dat[0];
// extern MSN_LOAD_DAT scn1120_load[0];
// extern u_short scn1120_del_dat[0];
// extern MSN_LOAD_DAT scn1170_load[0];
// extern u_short scn1170_del_dat[0];
// extern MSN_LOAD_DAT scn1150_load[0];
// extern u_short scn1150_del_dat[0];
// extern MSN_LOAD_DAT scn1180_load[0];
// extern u_short scn1180_del_dat[0];
// extern MSN_LOAD_DAT scn1230_load[0];
// extern u_short scn1230_del_dat[0];
// extern MSN_LOAD_DAT scn1220_load[0];
// extern u_short scn1220_del_dat[0];
// extern MSN_LOAD_DAT scn1260_load[0];
// extern u_short scn1260_del_dat[0];
// extern MSN_LOAD_DAT scn1250_load[0];
// extern u_short scn1250_del_dat[0];
// extern MSN_LOAD_DAT scn1280_load[0];
// extern u_short scn1280_del_dat[0];
// extern MSN_LOAD_DAT scn1301_load[0];
// extern u_short scn1301_del_dat[0];
// extern MSN_LOAD_DAT scn1320_load[0];
// extern u_short scn1320_del_dat[0];
// extern MSN_LOAD_DAT scn1330_load[0];
// extern u_short scn1330_del_dat[0];
// extern MSN_LOAD_DAT scn1410_load[0];
// extern u_short scn1410_del_dat[0];
// extern SCN_LOAD_DAT scn_load1[0];
// extern MSN_LOAD_DAT msn2_title_load_dat[0];
// extern MSN_LOAD_DAT scn2013_load[0];
// extern u_short scn2013_del_dat[0];
// extern MSN_LOAD_DAT scn2160_load[0];
// extern u_short scn2160_del_dat[0];
// extern MSN_LOAD_DAT scn2020_load[0];
// extern u_short scn2020_del_dat[0];
// extern MSN_LOAD_DAT scn2030_load[0];
// extern u_short scn2030_del_dat[0];
// extern MSN_LOAD_DAT scn2100_load[0];
// extern u_short scn2100_del_dat[0];
// extern MSN_LOAD_DAT scn2040_load[0];
// extern u_short scn2040_del_dat[0];
// extern MSN_LOAD_DAT scn2170_load[0];
// extern u_short scn2170_del_dat[0];
// extern MSN_LOAD_DAT scn2060_load[0];
// extern u_short scn2060_del_dat[0];
// extern MSN_LOAD_DAT scn2062_load[0];
// extern u_short scn2062_del_dat[0];
// extern MSN_LOAD_DAT scn2070_load[0];
// extern u_short scn2070_del_dat[0];
// extern MSN_LOAD_DAT scn2072_load[0];
// extern u_short scn2072_del_dat[0];
// extern MSN_LOAD_DAT scn2090_load[0];
// extern u_short scn2090_del_dat[0];
// extern MSN_LOAD_DAT scn2092_load[0];
// extern u_short scn2092_del_dat[0];
// extern MSN_LOAD_DAT scn2130_load[0];
// extern u_short scn2130_del_dat[0];
// extern MSN_LOAD_DAT scn2132_load[0];
// extern u_short scn2132_del_dat[0];
// extern MSN_LOAD_DAT scn2140_load[0];
// extern u_short scn2140_del_dat[0];
// extern MSN_LOAD_DAT scn2141_load[0];
// extern u_short scn2141_del_dat[0];
// extern MSN_LOAD_DAT scn2150_load[0];
// extern u_short scn2150_del_dat[0];
// extern SCN_LOAD_DAT scn_load2[0];
// extern MSN_LOAD_DAT msn3_title_load_dat[0];
// extern MSN_LOAD_DAT scn3020_load[0];
// extern u_short scn3020_del_dat[0];
// extern MSN_LOAD_DAT scn3030_load[0];
// extern u_short scn3030_del_dat[0];
// extern MSN_LOAD_DAT scn3100_load[0];
// extern u_short scn3100_del_dat[0];
// extern MSN_LOAD_DAT scn3050_load[0];
// extern u_short scn3050_del_dat[0];
// extern MSN_LOAD_DAT scn3110_load[0];
// extern u_short scn3110_del_dat[0];
// extern MSN_LOAD_DAT scn3060_load[0];
// extern u_short scn3060_del_dat[0];
// extern MSN_LOAD_DAT scn3070_load[0];
// extern u_short scn3070_del_dat[0];
// extern MSN_LOAD_DAT scn4900_load[0];
// extern u_short scn4900_del_dat[0];
// extern MSN_LOAD_DAT scn4901_load[0];
// extern u_short scn4901_del_dat[0];
// extern SCN_LOAD_DAT scn_load3[0];
// extern MSN_LOAD_DAT msn4_title_load_dat[0];
// extern MSN_LOAD_DAT scn4011_load[0];
// extern u_short scn4011_del_dat[0];
// extern MSN_LOAD_DAT scn4020_load[0];
// extern u_short scn4020_del_dat[0];
// extern MSN_LOAD_DAT scn4040_load[0];
// extern u_short scn4040_del_dat[0];
// extern MSN_LOAD_DAT scn4042_load[0];
// extern u_short scn4042_del_dat[0];
// extern MSN_LOAD_DAT scn4030_load[0];
// extern u_short scn4030_del_dat[0];
// extern MSN_LOAD_DAT scn4050_load[0];
// extern u_short scn4050_del_dat[0];
// extern MSN_LOAD_DAT scn4070_load[0];
// extern u_short scn4070_del_dat[0];
// extern SCN_LOAD_DAT scn_load4[0];
// extern MSN_LOAD_DAT *msn_title_load_dat[0];
// extern u_char msn_start_floor[0];
// extern u_char msn_start_room[0];
// extern SCN_LOAD_DAT *scn_load[0];
// extern SPRT_SDAT msn_title_sp_bak[0];
// extern SPRT_SDAT msn_title00_sp_flr[0];
// extern SPRT_SDAT msn_title00_sp_ttl[0];
// extern SPRT_SDAT msn_title01_sp_flr[0];
// extern SPRT_SDAT msn_title01_sp_ttl[0];
// extern SPRT_SDAT msn_title02_sp_flr[0];
// extern SPRT_SDAT msn_title02_sp_ttl[0];
// extern SPRT_SDAT msn_title03_sp_flr[0];
// extern SPRT_SDAT msn_title03_sp_ttl[0];
// extern SPRT_SDAT msn_title04_sp_flr[0];
// extern SPRT_SDAT msn_title04_sp_ttl[0];
// extern u_char msn_title_sp_flr_no[0];
// extern u_char msn_title_flr_sp_num[0];
// extern u_char msn_title_sp_ttl_no[0];
// extern u_char msn_title_ttl_sp_num[0];
// extern SPRT_SDAT *msn_title_sp_flr[0];
// extern SPRT_SDAT *msn_title_sp_ttl[0];
// extern SPRT_SDAT stg_title_sp_bak[0];
// extern SPRT_SDAT stg_title_sp_flr[0];
// extern SPRT_SDAT stg_title_sp_ttl[0];
extern MSN_LOAD_DAT load_dat_wrk[40];
// extern MSN_TITLE_WRK mttl_wrk;
// extern EVENT_LOAD_WRK ev_load_wrk;

void MissionTitleInit(int msn_no);
int MissionTitleMain(int msn_no);
int MissionTitleLoad(int msn_no);
int MissionDataLoadReq(MSN_LOAD_DAT *dat);
void MissionDataLoadAfterInit(MSN_LOAD_DAT *dat);
void DataLoadWrkInit();
void SetDataLoadWrk(MSN_LOAD_DAT *dat);
// void DelDataLoadWrk(u_short file_no);
u_int GetLoadDataAddr(u_short file_no);
void SortLoadDataAddr();
void MissionTitleDisp(int msn_no);
void StageTitleDisp(int msn_no);
void EventLoadDataInit();
int EventLoadData(u_char load_no);
int GetLoadGhostInfo(u_char *load_inf);
void MikuCGDisp();
void RoomLoadReq(int load_room);

#endif // INGAME_EVENT_EV_LOAD_H
