#ifndef INGAME_MAP_FURN_DAT_H
#define INGAME_MAP_FURN_DAT_H

#include "typedefs.h"
#include "furn_types.h"
#include "graphics/graph3d/light_types.h"

extern FURN_DAT furn_dat[];
// extern u_int furn_attr_dat[0][5];
// extern sceVu0FVECTOR furn_photo_center00[0];
// extern sceVu0FVECTOR furn_photo_center01[0];
// extern sceVu0FVECTOR furn_photo_center02[0];
// extern sceVu0FVECTOR furn_photo_center03[0];
// extern sceVu0FVECTOR furn_photo_center04[0];
// extern sceVu0FVECTOR furn_photo_center05[0];
// extern sceVu0FVECTOR furn_photo_center06[0];
// extern sceVu0FVECTOR furn_photo_center07[0];
// extern sceVu0FVECTOR furn_photo_center08[0];
// extern sceVu0FVECTOR furn_photo_center09[0];
// extern sceVu0FVECTOR furn_photo_center10[0];
// extern sceVu0FVECTOR furn_photo_center11[0];
// extern sceVu0FVECTOR furn_photo_center12[0];
// extern sceVu0FVECTOR furn_photo_center13[0];
// extern sceVu0FVECTOR furn_photo_center14[0];
// extern sceVu0FVECTOR furn_photo_center15[0];
// extern sceVu0FVECTOR furn_photo_center16[0];
// extern sceVu0FVECTOR furn_photo_center17[0];
// extern sceVu0FVECTOR furn_photo_center18[0];
// extern sceVu0FVECTOR furn_photo_center19[0];
// extern sceVu0FVECTOR furn_photo_center20[0];
// extern sceVu0FVECTOR furn_photo_center21[0];
// extern sceVu0FVECTOR furn_photo_center22[0];
// extern sceVu0FVECTOR furn_photo_center23[0];
// extern sceVu0FVECTOR furn_photo_center24[0];
// extern sceVu0FVECTOR furn_photo_center25[0];
// extern sceVu0FVECTOR furn_photo_center26[0];
// extern sceVu0FVECTOR furn_photo_center27[0];
// extern sceVu0FVECTOR furn_photo_center28[0];
// extern sceVu0FVECTOR furn_photo_center29[0];
// extern sceVu0FVECTOR furn_photo_center30[0];
// extern sceVu0FVECTOR furn_photo_center31[0];
// extern sceVu0FVECTOR furn_photo_center32[0];
// extern sceVu0FVECTOR furn_photo_center33[0];
// extern sceVu0FVECTOR furn_photo_center34[0];
// extern sceVu0FVECTOR furn_photo_center35[0];
// extern sceVu0FVECTOR furn_photo_center36[0];
// extern sceVu0FVECTOR furn_photo_center37[0];
// extern sceVu0FVECTOR furn_photo_center38[0];
// extern sceVu0FVECTOR furn_photo_center39[0];
// extern sceVu0FVECTOR furn_photo_center40[0];
// extern sceVu0FVECTOR furn_photo_center41[0];
// extern sceVu0FVECTOR furn_photo_center42[0];
// extern sceVu0FVECTOR furn_photo_center43[0];
// extern sceVu0FVECTOR furn_photo_center44[0];
// extern sceVu0FVECTOR furn_photo_center45[0];
// extern sceVu0FVECTOR furn_photo_center46[0];
// extern sceVu0FVECTOR furn_photo_center47[0];
// extern sceVu0FVECTOR furn_photo_center48[0];
// extern sceVu0FVECTOR furn_photo_center49[0];
// extern sceVu0FVECTOR furn_photo_center50[0];
// extern sceVu0FVECTOR furn_photo_center51[0];
// extern sceVu0FVECTOR furn_photo_center52[0];
// extern sceVu0FVECTOR furn_photo_center53[0];
// extern sceVu0FVECTOR furn_photo_center54[0];
// extern sceVu0FVECTOR furn_photo_center55[0];
// extern sceVu0FVECTOR furn_photo_center56[0];
// extern sceVu0FVECTOR furn_photo_center57[0];
// extern sceVu0FVECTOR furn_photo_center58[0];
// extern sceVu0FVECTOR furn_photo_center59[0];
// extern sceVu0FVECTOR furn_photo_center60[0];
// extern sceVu0FVECTOR furn_photo_center61[0];
// extern sceVu0FVECTOR furn_photo_center62[0];
// extern sceVu0FVECTOR furn_photo_center63[0];
// extern sceVu0FVECTOR furn_photo_center64[0];
// extern sceVu0FVECTOR furn_photo_center65[0];
// extern sceVu0FVECTOR furn_photo_center66[0];
// extern sceVu0FVECTOR furn_photo_center67[0];
// extern sceVu0FVECTOR furn_photo_center68[0];
// extern sceVu0FVECTOR furn_photo_center69[0];
// extern sceVu0FVECTOR furn_photo_center70[0];
// extern sceVu0FVECTOR furn_photo_center71[0];
// extern sceVu0FVECTOR furn_photo_center72[0];
// extern sceVu0FVECTOR furn_photo_center73[0];
// extern sceVu0FVECTOR furn_photo_center74[0];
// extern sceVu0FVECTOR furn_photo_center75[0];
// extern sceVu0FVECTOR furn_photo_center76[0];
// extern sceVu0FVECTOR furn_photo_center77[0];
// extern sceVu0FVECTOR furn_photo_center78[0];
// extern sceVu0FVECTOR furn_photo_center79[0];
// extern sceVu0FVECTOR furn_photo_center80[0];
// extern sceVu0FVECTOR furn_photo_center81[0];
// extern sceVu0FVECTOR furn_photo_center82[0];
// extern sceVu0FVECTOR furn_photo_center83[0];
// extern sceVu0FVECTOR furn_photo_center84[0];
// extern sceVu0FVECTOR furn_photo_center85[0];
// extern sceVu0FVECTOR furn_photo_center86[0];
// extern sceVu0FVECTOR furn_photo_center87[0];
// extern sceVu0FVECTOR furn_photo_center88[0];
// extern sceVu0FVECTOR furn_photo_center89[0];
// extern sceVu0FVECTOR furn_photo_center90[0];
// extern sceVu0FVECTOR furn_photo_center91[0];
// extern sceVu0FVECTOR furn_photo_center92[0];
// extern sceVu0FVECTOR furn_photo_center93[0];
// extern sceVu0FVECTOR furn_photo_center94[0];
// extern sceVu0FVECTOR furn_photo_center95[0];
// extern sceVu0FVECTOR furn_photo_center96[0];
// extern sceVu0FVECTOR furn_photo_center97[0];
// extern sceVu0FVECTOR furn_photo_center98[0];
// extern sceVu0FVECTOR furn_photo_center99[0];
// extern sceVu0FVECTOR furn_photo_center100[0];
// extern sceVu0FVECTOR furn_photo_center101[0];
// extern sceVu0FVECTOR furn_photo_center102[0];
extern sceVu0FVECTOR *fpc_dat[];
// extern u_char fpc_rot_dat[0][8];

FURN_DAT* GetFurnDatP(u_short furn_id);

#endif // INGAME_MAP_FURN_DAT_H
