#ifndef INGAME_MAP_FURN_DAT_H
#define INGAME_MAP_FURN_DAT_H

#include "typedefs.h"
#include "furn_types.h"
#include "graphics/graph3d/light_types.h"

extern FURN_DAT furn_dat[];
extern u_int furn_attr_dat[][5];
// extern sceVu0FVECTOR furn_photo_center00[];
// extern sceVu0FVECTOR furn_photo_center01[];
// extern sceVu0FVECTOR furn_photo_center02[];
// extern sceVu0FVECTOR furn_photo_center03[];
// extern sceVu0FVECTOR furn_photo_center04[];
// extern sceVu0FVECTOR furn_photo_center05[];
// extern sceVu0FVECTOR furn_photo_center06[];
// extern sceVu0FVECTOR furn_photo_center07[];
// extern sceVu0FVECTOR furn_photo_center08[];
// extern sceVu0FVECTOR furn_photo_center09[];
// extern sceVu0FVECTOR furn_photo_center10[];
// extern sceVu0FVECTOR furn_photo_center11[];
// extern sceVu0FVECTOR furn_photo_center12[];
// extern sceVu0FVECTOR furn_photo_center13[];
// extern sceVu0FVECTOR furn_photo_center14[];
// extern sceVu0FVECTOR furn_photo_center15[];
// extern sceVu0FVECTOR furn_photo_center16[];
// extern sceVu0FVECTOR furn_photo_center17[];
// extern sceVu0FVECTOR furn_photo_center18[];
// extern sceVu0FVECTOR furn_photo_center19[];
// extern sceVu0FVECTOR furn_photo_center20[];
// extern sceVu0FVECTOR furn_photo_center21[];
// extern sceVu0FVECTOR furn_photo_center22[];
// extern sceVu0FVECTOR furn_photo_center23[];
// extern sceVu0FVECTOR furn_photo_center24[];
// extern sceVu0FVECTOR furn_photo_center25[];
// extern sceVu0FVECTOR furn_photo_center26[];
// extern sceVu0FVECTOR furn_photo_center27[];
// extern sceVu0FVECTOR furn_photo_center28[];
// extern sceVu0FVECTOR furn_photo_center29[];
// extern sceVu0FVECTOR furn_photo_center30[];
// extern sceVu0FVECTOR furn_photo_center31[];
// extern sceVu0FVECTOR furn_photo_center32[];
// extern sceVu0FVECTOR furn_photo_center33[];
// extern sceVu0FVECTOR furn_photo_center34[];
// extern sceVu0FVECTOR furn_photo_center35[];
// extern sceVu0FVECTOR furn_photo_center36[];
// extern sceVu0FVECTOR furn_photo_center37[];
// extern sceVu0FVECTOR furn_photo_center38[];
// extern sceVu0FVECTOR furn_photo_center39[];
// extern sceVu0FVECTOR furn_photo_center40[];
// extern sceVu0FVECTOR furn_photo_center41[];
// extern sceVu0FVECTOR furn_photo_center42[];
// extern sceVu0FVECTOR furn_photo_center43[];
// extern sceVu0FVECTOR furn_photo_center44[];
// extern sceVu0FVECTOR furn_photo_center45[];
// extern sceVu0FVECTOR furn_photo_center46[];
// extern sceVu0FVECTOR furn_photo_center47[];
// extern sceVu0FVECTOR furn_photo_center48[];
// extern sceVu0FVECTOR furn_photo_center49[];
// extern sceVu0FVECTOR furn_photo_center50[];
// extern sceVu0FVECTOR furn_photo_center51[];
// extern sceVu0FVECTOR furn_photo_center52[];
// extern sceVu0FVECTOR furn_photo_center53[];
// extern sceVu0FVECTOR furn_photo_center54[];
// extern sceVu0FVECTOR furn_photo_center55[];
// extern sceVu0FVECTOR furn_photo_center56[];
// extern sceVu0FVECTOR furn_photo_center57[];
// extern sceVu0FVECTOR furn_photo_center58[];
// extern sceVu0FVECTOR furn_photo_center59[];
// extern sceVu0FVECTOR furn_photo_center60[];
// extern sceVu0FVECTOR furn_photo_center61[];
// extern sceVu0FVECTOR furn_photo_center62[];
// extern sceVu0FVECTOR furn_photo_center63[];
// extern sceVu0FVECTOR furn_photo_center64[];
// extern sceVu0FVECTOR furn_photo_center65[];
// extern sceVu0FVECTOR furn_photo_center66[];
// extern sceVu0FVECTOR furn_photo_center67[];
// extern sceVu0FVECTOR furn_photo_center68[];
// extern sceVu0FVECTOR furn_photo_center69[];
// extern sceVu0FVECTOR furn_photo_center70[];
// extern sceVu0FVECTOR furn_photo_center71[];
// extern sceVu0FVECTOR furn_photo_center72[];
// extern sceVu0FVECTOR furn_photo_center73[];
// extern sceVu0FVECTOR furn_photo_center74[];
// extern sceVu0FVECTOR furn_photo_center75[];
// extern sceVu0FVECTOR furn_photo_center76[];
// extern sceVu0FVECTOR furn_photo_center77[];
// extern sceVu0FVECTOR furn_photo_center78[];
// extern sceVu0FVECTOR furn_photo_center79[];
// extern sceVu0FVECTOR furn_photo_center80[];
// extern sceVu0FVECTOR furn_photo_center81[];
// extern sceVu0FVECTOR furn_photo_center82[];
// extern sceVu0FVECTOR furn_photo_center83[];
// extern sceVu0FVECTOR furn_photo_center84[];
// extern sceVu0FVECTOR furn_photo_center85[];
// extern sceVu0FVECTOR furn_photo_center86[];
// extern sceVu0FVECTOR furn_photo_center87[];
// extern sceVu0FVECTOR furn_photo_center88[];
// extern sceVu0FVECTOR furn_photo_center89[];
// extern sceVu0FVECTOR furn_photo_center90[];
// extern sceVu0FVECTOR furn_photo_center91[];
// extern sceVu0FVECTOR furn_photo_center92[];
// extern sceVu0FVECTOR furn_photo_center93[];
// extern sceVu0FVECTOR furn_photo_center94[];
// extern sceVu0FVECTOR furn_photo_center95[];
// extern sceVu0FVECTOR furn_photo_center96[];
// extern sceVu0FVECTOR furn_photo_center97[];
// extern sceVu0FVECTOR furn_photo_center98[];
// extern sceVu0FVECTOR furn_photo_center99[];
// extern sceVu0FVECTOR furn_photo_center100[];
// extern sceVu0FVECTOR furn_photo_center101[];
// extern sceVu0FVECTOR furn_photo_center102[];
extern sceVu0FVECTOR *fpc_dat[];
// extern u_char fpc_rot_dat[][8];

FURN_DAT* GetFurnDatP(u_short furn_id);

#endif // INGAME_MAP_FURN_DAT_H
